{% set name = "bilby" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b90491185723dfe5a741ffceea0dbeb84ef24183200411abfc451e813949dd4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bilby_plot = cli_bilby.plot_multiple_posteriors:main
    - bilby_result = cli_bilby.bilby_result:main

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - corner
    - dill
    - dynesty
    - emcee
    - h5py
    - matplotlib-base >=2.1
    - mock
    - numpy
    - pandas
    - python >=3.5
    - scipy >=0.16
    - tqdm
    - astropy

test:
  requires:
    - gwpy
    - pip
    - python-lal
    - python-lalsimulation
  imports:
    - bilby
    - bilby.core
    - bilby.core.sampler
    - bilby.gw
    - bilby.gw.detector
    - bilby.gw.sampler
    - bilby.hyper
    - cli_bilby
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - bilby_plot --help
    - bilby_result --help
    # check PSD from file works (validates data files)
    - python -c "from bilby.gw.detector import PowerSpectralDensity; print(PowerSpectralDensity.from_aligo().psd_array)"

about:
  home: https://git.ligo.org/lscsoft/bilby
  dev_url: https://git.ligo.org/lscsoft/bilby
  doc_url: https://lscsoft.docs.ligo.org/bilby/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A user-friendly Bayesian inference library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
